### ISSUE TITLE
Add examples for correct implementation to documentation

### ISSUE THREAD

**Issue by netcicd** [cisco-developer/api-insights#81]
In the documentation referenced when investigating an error, it explains what the error is. Adding an example of an expected implementation would save hours when debugging.

**Comment by npateriya** [comment]
@netcicd Can you please provide a sample schema document and more details on areas where examples would be helpful.

**Comment by netcicd** [comment]
[bizportal-0.0.1-0.2.zip](https://github.com/cisco-developer/api-insights/files/10729680/bizportal-0.0.1-0.2.zip)
The first error point to https://developer.cisco.com/docs/api-insights/#!rest-style/standard-response-headers and it shows the output in the browser, but what needs to be added  in the yml is:
paths:
  /tenants/:
    post:
      responses:
          headers:
            Location:
              type: string
              format: url
            Date: 
              type: string
              format: date
            TrackingId: 
              type: string
              format: uuid
It took quite some time to figure this out...

**Comment by npateriya** [comment]
We have positive and negative test case sample OAS doc for each scenario in [api-insights-openapi-rulesets/tests](https://github.com/cisco-developer/api-insights-openapi-rulesets/tree/main/test/resources), we will look how to effectively reference those in documents.

For example below is a reference sample for date-reference-requirement (please refer those till we have documents updated)
https://github.com/cisco-developer/api-insights-openapi-rulesets/blob/main/test/resources/date-response-header-requirement/positive.yml#L24

**Comment by netcicd** [comment]
OK, I managed to fix all errors but one: Error representations include a useful human-readable message.
[bis2.zip](https://github.com/cisco-developer/api-insights/files/10742092/bis2.zip)

From the examples you listed and the links above I cannot find what to change. I dropped in the latest version

**Comment by npateriya** [comment]
> OK, I managed to fix all errors but one: Error representations include a useful human-readable message. [bis2.zip](https://github.com/cisco-developer/api-insights/files/10742092/bis2.zip)
> 
> From the examples you listed and the links above I cannot find what to change. I dropped in the latest version

Rules is checking property named "message" in the error model. Most of OAS ref doc refer that property as message in doc https://spec.openapis.org/oas/v3.0.3#models-with-composition ( More of best practice  )
I think bis2 API error model field is called 'detail'.

**Comment by netcicd** [comment]
thx. no errors anymore
